### ISSUE TITLE
Issue with welcoming users

### ISSUE THREAD

**Issue by AntoineDeveloper** [AntoineSCAG/HexeDocs#1]
# NEW ISSUE

## Issue
Welcoming does not work anymore for now, Hexe does not welcome users anymore

## Cause
The cause of this initial problem is a guild intent permission that is needing verification from discord's side to be enabled

## Consequences
The welcoming will not work until Discord enables this feature for us

## Approximate time before resolution
Around 2-3 days I believe

**Comment by Itsrkb** [comment]
HEEEYYY HEEYYYYYY WHAT A PADO IN MAH BAYYYY BAY
